plugins {
    id 'com.android.application'
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "kr.co.todoc.cochlear.implant.ota"
        minSdk 23 // Android 6.0 (Marshmallow)
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    signingConfigs {
        config {
            storeFile file('..\\app\\external\\remote_app_key_store_file.jks')
            storePassword '!Todoc0987-82%^!'
            keyAlias 'key0'
            keyPassword '!Todoc0987-82%^!'
        }
    }

    buildFeatures {
        viewBinding = true
        dataBinding = true
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.config
        }
        release {
            signingConfig signingConfigs.config
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'todoc.cochlear.remoteapp.activity'
    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
    compileSdk 34
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    // Room
    def room_version = "2.7.1"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    // optional - RxJava support for Room
    implementation "androidx.room:room-rxjava2:$room_version"

    // optional - Guava support for Room, including Optional and ListenableFuture
    implementation "androidx.room:room-guava:$room_version"

    // optional - Test helpers
    testImplementation "androidx.room:room-testing:$room_version"

    def lifecycle_version = "2.9.1"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:lifecycle_version"

//    implementation 'com.github.mmin18:realtimeblurview:1.2.1'
    implementation 'com.skyfishjy.ripplebackground:library:1.0.1'
}